### ISSUE TITLE
miui工具箱

### ISSUE THREAD

**Issue by 2772457192** [CoolestEnoch/MIUI_Tools#1]
工具箱是用在平板上的吗？

**Comment by CoolestEnoch** [comment]
我现在就在小米M2105K81C平板的稳定版MIUI上用。~~但是此模块的开发现在已摆烂~~

**Comment by 2772457192** [comment]
三星平板s7root加lsp刷这模块能不能和小米手机互联妙享？

**Comment by CoolestEnoch** [comment]
为了防止出现预期以外的bug，我做了MIUI系统验证。MIUI专属功能在仅会在MIUI12.5及以上系统与Joy UI上启用，其余系统会自动禁用。你要是想开启，自行下载源码重编译。
ps.本模块本来就没有让设备和小米设备互联的能力，只是解除了MIUI pad中的一个机型校验以达到平板能连电脑MIUI+。

**Comment by 2772457192** [comment]
多谢解答！
